### ISSUE TITLE
JNSQ has wrong days after first year

### ISSUE THREAD

**Issue by linuxgurugamer** [Kopernicus/Kronometer#13] opened 2021-01-20 05:26 UTC
JNSQ with RTB Kopernicus, KSP 1.10.1

After day 365, goes to Y2, D00

This pic showing Y2 D00, 0:00:05 day is wrong for y2

https://i.imgur.com/ka0ac9D.png

![ksp_x64_dbg_2021-01-19_23-47-04](https://user-images.githubusercontent.com/1630166/105131056-2c607a00-5ab6-11eb-8cfd-533943bd03d8.png)

**Comment by Sigma88** [comment] 2021-01-20 15:29
this is not necessarily a bug, in some circumstances it is expected to get day 0

I will look into it to understand if it's an issue with how JNSQ-Kronometer compatibility is setup or if it is an actual bug in kronometer itself

**Comment by Sigma88** [comment] 2021-01-20 15:37
this is the file in JNSQ that handles kronometer,

https://github.com/Galileo88/JNSQ/blob/master/GameData/JNSQ/JNSQ_Configs/Kronometer.cfg

it does not change the parameter `useLeapYears` which in Kronometer is `false` by default

https://github.com/Kopernicus/Kronometer/blob/master/Distribution/Release/GameData/Kronometer/Settings.cfg#L5

this will result in years starting with day0 when the year starts halfway through a day.

to get the intended behaviour the JNSQ cfg should also have the line:

```
@useLeapYears = true
```

however I would have expected the year to end with day 366 if this was the issue, so I am a bit confused if you say the first year ends with day 365....

**Comment by Sigma88** [comment] 2021-01-24 12:35
this is fixed in the new version I am about to release

**Closed as completed by Sigma88** 2021-01-24 12:35 UTC

**Comment by linuxgurugamer** [comment] 2021-01-24 14:17
Thank you

**Comment by Sigma88** [comment] 2021-01-24 14:21
no problem

notice that there is a bug in kopernicus that affects kronometer as well.

I found the bug since I was getting inconsistent results while fixing kronometer. that bug has already been fixed and the fix should be included in the next bleeding edge release by @R-T-B
